version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ride_pg
    restart: always
    environment:
      POSTGRES_USER: rideuser
      POSTGRES_PASSWORD: ridepass
      POSTGRES_DB: ride_booking_dev
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
